# Generated by Django 3.2.7 on 2021-09-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mlimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageurl', models.TextField()),
            ],
        ),
    ]
